/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHealthConnectHcwebhookRouteImport } from './routes/api/public/health-connect/hcwebhook'
import { Route as ApiPublicHealthConnectSyncRouteImport } from './routes/api/public/health-connect/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthConnectHcwebhookRoute =
  ApiPublicHealthConnectHcwebhookRouteImport.update({
    id: '/api/public/health-connect/hcwebhook',
    path: '/api/public/health-connect/hcwebhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthConnectSyncRoute =
  ApiPublicHealthConnectSyncRouteImport.update({
    id: '/api/public/health-connect/sync',
    path: '/api/public/health-connect/sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/health-connect/hcwebhook': typeof ApiPublicHealthConnectHcwebhookRoute
  '/api/public/health-connect/sync': typeof ApiPublicHealthConnectSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/health-connect/hcwebhook': typeof ApiPublicHealthConnectHcwebhookRoute
  '/api/public/health-connect/sync': typeof ApiPublicHealthConnectSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/health-connect/hcwebhook': typeof ApiPublicHealthConnectHcwebhookRoute
  '/api/public/health-connect/sync': typeof ApiPublicHealthConnectSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/health-connect/hcwebhook'
    | '/api/public/health-connect/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/health-connect/hcwebhook'
    | '/api/public/health-connect/sync'
  id:
    | '__root__'
    | '/'
    | '/api/public/health-connect/hcwebhook'
    | '/api/public/health-connect/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHealthConnectHcwebhookRoute: typeof ApiPublicHealthConnectHcwebhookRoute
  ApiPublicHealthConnectSyncRoute: typeof ApiPublicHealthConnectSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-connect/hcwebhook': {
      id: '/api/public/health-connect/hcwebhook'
      path: '/api/public/health-connect/hcwebhook'
      fullPath: '/api/public/health-connect/hcwebhook'
      preLoaderRoute: typeof ApiPublicHealthConnectHcwebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-connect/sync': {
      id: '/api/public/health-connect/sync'
      path: '/api/public/health-connect/sync'
      fullPath: '/api/public/health-connect/sync'
      preLoaderRoute: typeof ApiPublicHealthConnectSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHealthConnectHcwebhookRoute: ApiPublicHealthConnectHcwebhookRoute,
  ApiPublicHealthConnectSyncRoute: ApiPublicHealthConnectSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
